apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby
  labels:
    app: dobby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dobby
  template:
    metadata:
      labels:
        app: dobby
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-geeknight: "kv/data/application/dobby"
        vault.hashicorp.com/agent-inject-template-geeknight: |
          {
          {{ with secret "kv/data/application/dobby" -}}
            "mysecret": "{{ .Data.data.mysecret }}"
          {{- end }}
          }
        vault.hashicorp.com/role: "geeknight"
    spec:
      serviceAccountName: "geeknight"
      containers:
        - name: geeknight
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444
          env:
            - name: INITIAL_DELAY
              value: "0"